__include__: [
  '../dataset/coco_detection.yml',
  '../runtime.yml',
  './include/dataloader.yml',
  './include/optimizer.yml',
  './include/rtdetr_r50vd.yml',
]

train_dataloader:
  dataset:
    ann_file: dataset/annotations/instances_crop_train2017.json

output_dir: ./output/rtdetr_r50vd_6x_coco3
